### ISSUE TITLE
add support for scan and scanstream

### ISSUE THREAD

**Issue by mahendraHegde** [jsumners/abstract-cache-redis#4]
Redis [scan](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwi9k_OY_sPvAhXOqksFHYQ6AzkQFjAAegQICBAD&url=https%3A%2F%2Fredis.io%2Fcommands%2Fscan&usg=AOvVaw1KO1z1QRP6YUc-9VVRaHqp) is a better alternative for `keys`. As the package already has support for keys its seems necessary to add support for `scan` and [scanStream](https://github.com/luin/ioredis#streamify-scanning) as well.

I'm willing to work on it, let me know what do you think @jsumners

**Comment by jsumners** [comment]
I'm willing to consider it.

**Comment by mahendraHegde** [comment]
@jsumners  I'll send PR
