### ISSUE TITLE
Redis went for a dual license

### ISSUE THREAD

**Issue by melroy89** [jsumners/abstract-cache-redis#7]
So Redis adopts for a dual license: https://redis.com/blog/redis-adopts-dual-source-available-licensing/

Could you support Dragonfly as a drop in replacement as well? If so, maybe update the README and an example for users who want to migrate to Dragonfly instead of Redis.

Or at least mention KeyDB: https://github.com/Snapchat/KeyDB

**Comment by melroy89** [comment]
Ow what about ValKey??

**Comment by jsumners** [comment]
People can use whatever db driver conforms to the known client API.

**Comment by melroy89** [comment]
Yes I know, my remark is maybe we should update the README accordingly, so people know they can use other redis alternatives, despite the `redis` in the name.
